### ISSUE TITLE
Working group charter

### ISSUE THREAD

**Issue by ehuss** [rust-lang-nursery/wg-grammar#1]
What is the charter of the working group?

The high-level purpose/goals/scope/deliverables of the group should probably go into the README.

I'll make a proposal, but please comment with your own thoughts!

-----

Goals:
* Satisfy [RFC 1331](https://github.com/rust-lang/rfcs/blob/master/text/1331-grammar-is-canonical.md) and produce a testable, canonical grammar for the Rust language.

Non-goals:
* Direct use within rustc, or any other existing tools.

The grammar's primary audiences are:
* Rust RFC authors who wish to propose and communicate changes.
* rustc and Rust tool developers who need an authoritative definition of the grammar.
* To assist documentation efforts to communicate valid Rust syntax to users.

**Comment by Centril** [comment]
I would potentially add a fourth point:
+ to facilitate the making of a language report / specification

tho this might also fit under:
> To assist documentation efforts to communicate valid Rust syntax to users.

Other than that it seems good.
