### ISSUE TITLE
CI: test harness against src/

### ISSUE THREAD

**Issue by Centril** [rust-lang-nursery/wg-grammar#12]
There's a large base of valid rust code and tests inside https://github.com/rust-lang/rust/tree/master/src ...

We should thus `git clone` or have the `rust-lang/rust` repo be a submodule in this repo and then run the harness against it.

We should then think about how to setup CI to nudge us towards parsing more...

Any ideas? maybe we can sort of set a "minimum number of successful parses" and then increase that number gradually as we flesh out the grammar?

**Comment by CAD97** [comment]
One caveat: we decided we wanted to start by targeting parsing stable code, right?

I'm uncertain how many of the compiler files are using unstable grammar and how many aren't.

**Comment by Centril** [comment]
Sure; I think we might want to restrict ourselves to that somehow...
But initially, it seems like an easy way to "just get started" to test against a large corpus so that we know if we are making progress or not... the idea is that "if the number goes up, we are on the right track" (where the number is the successful and full parses in https://github.com/rust-lang-nursery/wg-grammar/pull/10).

**Comment by matklad** [comment]
>We should thus git clone or have the rust-lang/rust repo be a submodule in this repo and then run the harness against it.

The problem with this idea would be that such test suite would contain many "duplicate" test and have a high degree of redundancy.

I think it would be useful (but definitely more work) to produce, by hand, a minimal test suite targeting syntax specifically, and then use the large existing corpus to find missing parts of the suite.

**Comment by eddyb** [comment]
For the record, this traversal (currently checking for ambiguity):

https://github.com/rust-lang-nursery/wg-grammar/blob/db81bad181c1dd64248ca6cc8be18c3fa897116d/src/bin/tester.rs#L79-L94

could be repurposed to also collect a set (effectively a coverage) of all the parse node kinds found in the parse forests resulting from parsing the test files.

That way, we'd be able to ensure that a minimal syntax test suite still covers the entire grammar *and* we can also measure redundancy between any pair of tests.

<hr/>

@nikomatsakis @eternaleye here's an even crazier idea: it should be possible to do a backtracking traversal over the grammar, making each parse node kind show at most once (to limit complexity), and picking all possible choices for `|` and `?` - that would give you a bunch of code examples.

**Comment by qmx** [comment]
fixed by #19
