### ISSUE TITLE
Grammar language

### ISSUE THREAD

**Issue by ehuss** [rust-lang-nursery/wg-grammar#2]
What language(s) will the grammar be written in?

What is the ultimate output of the group? I think qmx/centril said "a CFG textual representation of the grammar, that potentially could be consumed by both LALRPOP and GLL" but I'd like to know more exactly what that means.

I also think that the language used affects how ambiguities and precedence are expressed, and I think that's important to establish early in relation to issue #1.

**Comment by Centril** [comment]
I think @eddyb should fill in here :)

Using GLL in a textual format would be nice to detect ambiguities.
That way we can define the grammar in an easy way instead of doing convoluted tricks around precedence.

**Comment by Apanatshka** [comment]
I would like to suggest [SDF3](http://www.metaborg.org/en/latest/source/langdev/meta/lang/sdf3/index.html) as a grammar formalism to consider. It has support for context-free grammars with disambiguation annotations, and it includes negation as well so technically it's powerful enough to capture Boolean Grammars. There is also some built-in support for zero-or-more and one-or-more lists with separators. It _does_ assume it has full control over the grammar, including the lexical part. 
There is tooling available such as an editor in Eclipse, a parse-table generator for a particular SGLR parser implementation, as well the ability to generate an Eclipse editor which uses the grammar for highlighting, syntactic code completion, and code formatting.

**Comment by matklad** [comment]
Case study: Kotlin uses a plain text file for grammar spec. https://github.com/JetBrains/kotlin/blob/master/grammar/src/class.grm. The spec is not executable though, it exists only to render grammar on the docs website: https://github.com/JetBrains/kotlin/tree/master/grammar

**Comment by ehuss** [comment]
I thought it might be interested to do a survey of what other specs do.

C++: Annex A of [the standard](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf) includes a simple, "informative" grammar. It is extracted from the in-line grammar used throughout the [latex source](https://github.com/cplusplus/draft). This is very analogous to the Rust Reference, where we have a tool to extract the in-line grammar, but it is not currently in use.

Haskell: [Lexical structure](https://www.haskell.org/onlinereport/haskell2010/haskellch2.html) and [syntax reference](https://www.haskell.org/onlinereport/haskell2010/haskellch10.html)

C#: [Lexical structure](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure) with ANTLR grammar interspersed throughout.

Javascript: [Lexical grammar](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-ecmascript-language-lexical-grammar) and [grammar summary](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-grammar-summary) and [notation](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-notational-conventions). [Typescript](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#2.1) uses the same grammar.

Go: [Notation](https://golang.org/ref/spec#Notation) as EBNF interspersed throughout spec.

Swift: [Language reference](https://docs.swift.org/swift-book/ReferenceManual/AboutTheLanguageReference.html) and [summary](https://docs.swift.org/swift-book/ReferenceManual/zzSummaryOfTheGrammar.html).

Java: [Grammar notation](https://docs.oracle.com/javase/specs/jls/se11/html/jls-2.html) and [summary](https://docs.oracle.com/javase/specs/jls/se11/html/jls-19.html).

Ada: [Notation](http://www.ada-auth.org/standards/12rm/html/RM-1-1-4.html) and [summary](http://www.ada-auth.org/standards/12rm/html/RM-P.html).

**Comment by petrochenkov** [comment]
I'd suggest to use any language that's 1) supported by `lykenware/gll` implementation and 2) makes it impossible to break out of CFG.
If it implemented something like https://link.springer.com/chapter/10.1007%2F978-3-319-71734-0_3 already - great, we can use EBNF, if not BNF is not bad either.

(Not sure about filters, I think I'd prefer to see them in the spec only for true ambiguities, with everything else done through the grammar itself if possible.)

**Comment by eddyb** [comment]
I think we should consider the *syntax* of the grammar language orthogonal from the *features* of the grammar language/formalism.

You can see (most of) the "AST" of the grammar language used by `gll` in [`grammar::Rule`](https://docs.rs/gll/0.0.2/gll/grammar/enum.Rule.html).
On top of that, various sub-rules can be given a field/variant name.

Any syntax that can represent some or all of those context-free features (ignore the lookahead thing, that's only used in unrelated scannerless tests) can be turned into a `gll` `Grammar`, and the current syntax the `gll` crate currently takes in is just something we ended up settling on.

However, *there are no other features*, nor do I want to use something that *requires* more features to even generate a parser at all.
That is, IMO, the feature-set we should build a grammar upon is CFG, with some sugar (and we might add e.g. more kinds of lists to `gll`, if needed).

Declarative disambiguation *on top of that* would be nice, but I think we should first find a grammar that parses all Rust code out there *even if ambiguously*.

**EDIT**: if anyone wants to have a go at parsing some other grammar language into a `gll` `Grammar`, [this is what that looks like](https://github.com/lykenware/gll/blob/master/src/parse_grammar.rs).

**Comment by qmx** [comment]
@Centril should this be closed now that we settled for `.lyg` aka _Lykenware GLL's grammar format_?
